import { Info, Sparkles } from "lucide-react";
import { redirect } from "next/navigation";
import { ChatInterface } from "@/components/chat/chat-interface";
import { Card, CardContent } from "@/components/ui/card";
import { createSupabaseServer } from "@/lib/supabase/server";

export default async function ChatPage() {
  const supabase = await createSupabaseServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login");
  }

  return (
    <div className="space-y-10">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <div>
          <span className="text-[10px] font-black uppercase tracking-[0.2em] text-primary mb-2 block">
            Neural Interface
          </span>
          <h1 className="text-4xl md:text-5xl font-black tracking-tighter uppercase leading-none">
            AI Assistant
          </h1>
          <p className="text-muted-foreground font-medium mt-4">
            Direct uplink to the system's synthetic intelligence core.
          </p>
        </div>

        <div className="flex items-center gap-3 px-4 py-2 bg-primary/5 rounded-full border border-primary/10">
          <div className="size-2 rounded-full bg-primary animate-pulse" />
          <span className="text-[10px] font-black uppercase tracking-widest text-primary">
            Secure Uplink Active
          </span>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-8 items-start">
        <div className="lg:col-span-2">
          <ChatInterface />
        </div>

        <div className="space-y-6">
          <Card className="border-none shadow-sm bg-slate-900 text-white rounded-[2rem] overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <Sparkles className="size-20" />
            </div>
            <CardContent className="p-6 md:p-8 relative z-10">
              <h3 className="text-xl font-black uppercase tracking-tighter mb-4">
                Core Capabilities
              </h3>
              <ul className="space-y-4">
                {[
                  "Architectural Guidance",
                  "Code Synthesis & Review",
                  "Strategic Market Analysis",
                  "System Diagnostics",
                ].map((cap) => (
                  <li
                    key={cap}
                    className="flex items-center gap-3 text-xs font-bold uppercase tracking-tight text-slate-300"
                  >
                    <div className="size-1.5 rounded-full bg-primary" />
                    {cap}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card className="border-none shadow-sm bg-white rounded-[2rem] overflow-hidden border border-slate-100">
            <CardContent className="p-6 md:p-8 flex items-start gap-4">
              <div className="size-10 rounded-xl bg-slate-100 flex items-center justify-center text-slate-400 shrink-0">
                <Info className="size-5" />
              </div>
              <div>
                <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground mb-2">
                  Technical Note
                </p>
                <p className="text-xs font-medium text-slate-600 leading-relaxed">
                  Responses are generated by the configured LLM provider. Accuracy is subject to the
                  model's training parameters and current contextual window.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
